# Generated by Django 5.2.12 on 2026-04-10 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_image', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CrewMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('athlete', 'Athlete'), ('coach', 'Coach'), ('cox', 'Cox')], default='athlete', max_length=10)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.crew')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.profiles')),
            ],
            options={
                'unique_together': {('profile', 'crew')},
            },
        ),
        migrations.AddField(
            model_name='crew',
            name='members',
            field=models.ManyToManyField(related_name='crews', through='users.CrewMembership', to='users.profiles'),
        ),
    ]
