# Generated by Django 5.2.14 on 2026-05-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profiles_gender_dateofbirth_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='calendar_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
