version: "3.9"

services:
  web:
    build: .
    restart: always
    env_file: .env
    volumes:
      - ./static:/app/static:ro
      - ./static/images:/app/static/images
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static:ro
    depends_on:
      - web