# Generated by Django 5.2.12 on 2026-04-10 08:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('description', models.TextField(blank=True, null=True)),
                ('intensity', models.CharField(choices=[('T1', 'Warm up'), ('T2', 'Easy'), ('T3', 'Aerobic'), ('T4', 'Threshold'), ('T5', 'Maximum')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='users.crew')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.profiles')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='agenda.training')),
            ],
            options={
                'unique_together': {('training', 'athlete')},
            },
        ),
    ]
