# Generated by Django 5.2.12 on 2026-05-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='intensity',
            field=models.CharField(choices=[('T1', 'T1 - Warm up'), ('T2', 'T2 - Easy'), ('T3', 'T3 - Aerobic'), ('T4', 'T4 - Threshold'), ('T5', 'T5 - Maximum')], max_length=10),
        ),
    ]
