# Generated by Django 5.2.14 on 2026-05-19 10:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_training_intensity'),
        ('users', '0004_profiles_calendar_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyStats',
            fields=[
                ('date', models.DateField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resting_heartrate', models.IntegerField(blank=True, null=True)),
                ('hrv', models.IntegerField(blank=True, null=True)),
                ('body_battery', models.IntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodystats', to='users.profiles')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('profile', 'date')},
            },
        ),
    ]
